// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJ2W21D-Yv2_W9ZLRzYICEJ9KT8BVZws',
    appId: '1:667148335739:web:83659f17d7c41b534240de',
    messagingSenderId: '667148335739',
    projectId: 'kaskita-c5844',
    authDomain: 'kaskita-c5844.firebaseapp.com',
    storageBucket: 'kaskita-c5844.firebasestorage.app',
    measurementId: 'G-FVGHN2SNHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGcuXnGNgtbLyoGmAmX1oDwcN2mJsLiTk',
    appId: '1:667148335739:android:556e55de5aa97b2f4240de',
    messagingSenderId: '667148335739',
    projectId: 'kaskita-c5844',
    storageBucket: 'kaskita-c5844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBtQQ2xG79TY3g-MPp_XAXNOVcrt1lu18',
    appId: '1:667148335739:ios:af4096d321ebbec74240de',
    messagingSenderId: '667148335739',
    projectId: 'kaskita-c5844',
    storageBucket: 'kaskita-c5844.firebasestorage.app',
    iosBundleId: 'com.example.kaskita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBtQQ2xG79TY3g-MPp_XAXNOVcrt1lu18',
    appId: '1:667148335739:ios:af4096d321ebbec74240de',
    messagingSenderId: '667148335739',
    projectId: 'kaskita-c5844',
    storageBucket: 'kaskita-c5844.firebasestorage.app',
    iosBundleId: 'com.example.kaskita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrJ2W21D-Yv2_W9ZLRzYICEJ9KT8BVZws',
    appId: '1:667148335739:web:f7386b10797b908f4240de',
    messagingSenderId: '667148335739',
    projectId: 'kaskita-c5844',
    authDomain: 'kaskita-c5844.firebaseapp.com',
    storageBucket: 'kaskita-c5844.firebasestorage.app',
    measurementId: 'G-WND8Y03G35',
  );
}
